#!/bin/bash

DOCKER_DIR=$(dirname $(realpath $0))
source ${DOCKER_DIR}/../env js

case $1 in
'shell')
    COMMAND='bash'
    ;;
'frontend')
    PROXY_IP=$(${DOCKER_DIR}/../util/ip-address ${BACKEND_RUN_NAME})
    PROXY="http://${PROXY_IP}:8000/"
    COMMAND="npm run serve -- --env.proxy.target=${PROXY} --host=0.0.0.0"
    ;;
*)
    echo "../docker/js/start shell    bash"
    echo "../docker/js/start frontend Webpack dev. server"
    exit
    ;;
esac

echo Running from $(pwd)

if (docker ps | grep -q ${CONT_NAME})
then
    echo 'Container alreday running'

    docker container exec \
        --interactive --tty \
        --workdir ${CONT_WORK_DIR}/client \
        ${RUN_NAME} \
        ${COMMAND}
else
    echo 'Starting new container'

    docker build --tag ${CONT_NAME} ${DOCKER_DIR}

    docker run \
        --rm --interactive --tty \
        --workdir ${CONT_WORK_DIR}/client \
        --publish 9000:9000 \
        --user $(id -u):$(id -g) \
        --volume ${HOST_WORK_DIR}:${CONT_WORK_DIR} \
        --name ${RUN_NAME} \
        ${CONT_NAME} \
        ${COMMAND}
fi

