#!/bin/bash

VERSION=10.3
RUN_NAME=mariadb$(echo ${VERSION} | sed -e 's/[^0-9]//g')
DOCKER_DIR=$(realpath $(dirname $0))
EXEC="container exec --interactive"
MARIADB="mysql --user=root --password=root"
DB=ispyb_build
OPTION=''

cd $(echo $DOCKER_DIR | sed 's/docker/ispyb-database/g')

case $1 in
'log')
    JOB='run'
    OPTION='--general-log=1 --general-log-file=/var/lib/mysql/general.log'
    ;;
'dump')
    JOB='dump'
    ;;
'schema')
    JOB='dump'
    OPTION='--no-data'
    ;;
*)
    JOB=$1
    ;;
esac

case $JOB in
'run')
    CONTAINER="mariadb:${VERSION}"
    docker pull ${CONTAINER}

    THIS_DIR="$(pwd)"
    DB_DIR="${THIS_DIR}/storage/database"
    mkdir -p ${DB_DIR}
    
    docker run \
        --rm --interactive --tty \
        --volume ${DB_DIR}:/var/lib/mysql \
        --volume ${THIS_DIR}:/usr/local/src \
        --env MARIADB_ROOT_PASSWORD='root' \
        --publish 3306:3306 \
        --name=${RUN_NAME} \
        ${CONTAINER} ${OPTION} \
    ;;
'shell')
    docker ${EXEC} --tty ${RUN_NAME} bash
    ;;
'sql')
    [ -d ./storage/database/${DB}/ ] || DB=mysql
    docker ${EXEC} --tty ${RUN_NAME} ${MARIADB} --database=${DB}
    ;;
'dump')
    docker ${EXEC} --tty ${RUN_NAME} \
        mariadb-dump ${DB} ${OPTION} --user=root --password=root
    ;;
'create')
    CMD="DROP DATABASE IF EXISTS ${DB}; CREATE DATABASE ${DB};"
    docker ${EXEC} ${RUN_NAME} ${MARIADB} --execute="${CMD}"
    ;;
'import')
    cat $3 | docker ${EXEC} ${RUN_NAME} ${MARIADB} --database=${DB}
    ;;
*)
    echo "run from the project working directory"
    echo "../docker/mariadb run"
    echo "../docker/mariadb log              { same as run but with logging }"
    echo "../docker/mariadb shell"
    echo "../docker/mariadb sql"
    echo "../docker/mariadb dump"
    echo "../docker/mariadb schema"
    echo "../docker/mariadb create           { always create before import }"
    echo "../docker/mariadb import ____.sql"
    ;;
esac
