#!/bin/bash

source $(dirname $(realpath $0))/env

nmcli con up id 'Diamond Light Source'

if [ "$(ls -A ${HOST_FS_DIR})" ]
then
    echo 'network FS dir already mounted'
else
    echo 'Mounting network FS dir'
    mount ${HOST_FS_DIR}
fi

xfce4-terminal \
    --tab --command="../docker/php/start backend" --title='backend' \
    --tab --command="../docker/js/start frontend" --title='frontend'

