#!/bin/bash

DOCKER_DIR=$(dirname $(realpath $0))
source ${DOCKER_DIR}/../env mariadb

COMMAND="php /usr/local/bin/mysql-config.php ${CONT_WORK_DIR}"

if (docker ps | grep -q ${CONT_NAME})
then
    docker container exec \
        --interactive --tty \
        --workdir ${CONT_WORK_DIR} \
        ${RUN_NAME} \
        ${COMMAND}
else
    docker build --tag ${CONT_NAME} ${DOCKER_DIR}

    docker run \
        --rm --interactive --tty \
        --workdir ${CONT_WORK_DIR} \
        --volume ${HOST_WORK_DIR}:${CONT_WORK_DIR} \
        --name ${RUN_NAME} \
        ${CONT_NAME} \
        ${COMMAND}
fi
