#!/bin/bash

DOCKER_DIR=$(dirname $(realpath $0))
source ${DOCKER_DIR}/../env mariadb

echo Running from $(pwd)

docker build --tag ${CONT_NAME} ${DOCKER_DIR}

docker run \
    --rm --interactive --tty \
    --workdir ${CONT_WORK_DIR} \
    $(${DOCKER_DIR}/../dns-servers) \
    --volume ${HOST_WORK_DIR}:${CONT_WORK_DIR} \
    --name ${RUN_NAME} \
    ${CONT_NAME} \
    php /usr/local/bin/mysql-config.php ${CONT_WORK_DIR}

