#!/bin/bash

THIS_SCRIPT=$(basename $0)
DOCKER_DIR=$(dirname $(realpath $0))
source ${DOCKER_DIR}/../env php

if [[ ${THIS_SCRIPT} != 'start' ]]
then
    if (docker ps | grep -q ${CONT_NAME})
    then
        TTY=''
        case ${THIS_SCRIPT} in
        'php')
            COMMAND="php $@"
            ;;
        phpcs|phpmd)
            COMMAND="lint-docker ${THIS_SCRIPT} ${HOST_WORK_DIR} ${CONT_WORK_DIR} $@"
            ;;
        esac
    else
        exit
    fi
else
    echo Running from $(pwd)
    TTY='--tty'
    case $1 in
    'shell')
        COMMAND='bash'
        ;;
    'backend')
        COMMAND='php -S 0.0.0.0:8000'
        ;;
    *)
        echo "../docker/php/start shell    bash"
        echo "../docker/php/start backend  PHP dev. server"
        echo "../docker/php                Run PHP with params"
        echo "../docker/phpcs              Run PHP Code Sniffer"
        echo "../docker/phpmd              Run PHP Mess Detector"
        exit
        ;;
    esac
fi

if (docker ps | grep -q ${CONT_NAME})
then
    docker container exec \
        --interactive ${TTY} \
        --workdir ${CONT_WORK_DIR} \
        ${RUN_NAME} \
        ${COMMAND}
else
    docker build --tag ${CONT_NAME} ${DOCKER_DIR}

    docker run \
        --rm --interactive --tty \
        --workdir ${CONT_WORK_DIR} \
        --publish 8000:8000 \
        $(${DOCKER_DIR}/../dns-servers) \
        --user $(id -u):$(id -g) \
        --volume ${HOST_WORK_DIR}:${CONT_WORK_DIR} \
        --volume ${HOME}/.ssh:/home/dev/.ssh:ro \
        --volume ${HOST_FS_DIR}:/${CONT_FS_DIR} \
        --name ${RUN_NAME} \
        ${CONT_NAME} \
        ${COMMAND}
fi
